services:
  - type: web
    name: classroom-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: "e3f3fe7a187c926517987d6473183d6e"
      - key: MONGO_URI
        value: "mongodb+srv://jorgegajardop:primarykEyh0st@cluster0.zjkhiz7.mongodb.net/classroom?retryWrites=true&w=majority"
